### ISSUE TITLE
Fails to register .J file extension

### ISSUE THREAD

**Issue by mcandre** [tikkanz/j-vscode#1]
When this plugin is installed, `*.j` files continue to load as plain text files rather than J language files.

**Comment by tikkanz** [comment]
Note that `.j` is not a file extension used by the J language. Scripts usually use the `.ijs` extension ([J file extensions](https://stackoverflow.com/questions/7951111/whats-the-preferred-j-source-code-file-extension)). If you personally want to use `.j`, then you can set this up in your user settings.
