### ISSUE TITLE
Empty comment in j.tmLanguage.yaml#L110

### ISSUE THREAD

**Issue by vfcp** [tikkanz/j-vscode#2]
Hi!

I've found an issue related with commit 93f9a883743c5861a9f6b820bceaff42bea9f83c 

In: https://github.com/tikkanz/j-vscode/blob/b5c0e9a56595d468cd8859069639cfaaae6ff8f8/syntaxes/j.tmLanguage.yaml#L110 there's a comment entry with no value.
This is causing another issue in: https://github.com/tikkanz/JSyntax/blob/15126700d11205fa38f7a41c3f41504d0aedbe42/J.tmLanguage#L314 where we get a `<key>comment</key>` with no value which is not valid according Plist DTD (you can validate the generated xml at https://www.truugo.com/xml_validator/).

Providing a value for the comment or removing the comment entry would solve this issue.

**Comment by tikkanz** [comment]
Comment added and J.tmLanguage now validates.
